# use Ganache's forked mainnet mode as the default network
networks:
  default: polygon-main-fork
  kovan-fork:
      host: https://kovan.infura.io/v3/<KEY>
      cmd: ganache-cli
      cmd_settings:
        fork: kovan
        port: 8545
        gas_limit: 6721975
        accounts: 10
        evm_version: instabul
        mnemonic: brownie

wallets:
  from_mnemonic: 'keys'


# automatically fetch contract sources from Etherscan
autofetch_sources: False

# require OpenZepplin Contracts
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.0.2
  - OpenZeppelin/openzeppelin-contracts@3.4.0


# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.6.6
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.0.2'

reports:
  # exclude_paths:
  #   - contracts/test/Token.sol
  exclude_contracts:
    - SafeMath
